name: Flask Application CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rabin8866
          MYSQL_DATABASE: test_mydatabase
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask flask-mysqldb pytest

    - name: Create Test Database
      run: |
        mysql -u root -p 'rabin8866' -e "CREATE DATABASE IF NOT EXISTS test_mydatabase;"

    - name: Run tests
      env:
        MYSQL_HOST: localhost
        MYSQL_USER: root
        MYSQL_PASSWORD: rabin8866
        MYSQL_DB: test_mydatabase
      run: pytest